recipe/urls.py
""" Module for url names within project """
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('browse/', views.RecipeList.as_view(), name='browse_recipes'),
    path('add_recipe/', views.create_or_update_recipe, name='add_recipe'),
    path('edit_recipe/<int:recipe_pk>/', views.create_or_update_recipe, name='edit_recipe'),
    path('delete_recipe/<int:recipe_pk>/', views.delete_recipe, name='delete_recipe'),
    path('<int:recipe_pk>/', views.get_recipe_detail, name='get_recipe_detail'),
    path('<int:recipe_pk>/edit_comment/<int:comment_pk>',
         views.edit_comment, name='edit_comment'),
    path('<int:recipe_pk>/delete_comment/<int:comment_pk>',
         views.delete_comment, name='delete_comment'),
    path('create_meal_plan/', views.create_meal_plan, name='create_meal_plan'),
    path('browse_meal_plans/', views.MealPlanList.as_view(), name='browse_meal_plans'),
    path('meal_plan/<int:meal_plan_pk>/', views.get_meal_plan, name='get_meal_plan'),
    path('meal_plan-add_recipe', views.add_recipe_to_meal_plan, name='add_recipe_to_meal_plan')
]

recipe_project/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("", include("recipe.urls"), name="recipe-urls"),
]

recipe/models.py
""" Module for django data models """
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models


class Ingredient(models.Model):
    """
    Stores a single ingredient
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    """
    Stores a single recipe
    """
    STATUS = (
        (0, 'Draft'),
        (1, 'Published'),
    )
    DIFFICULTY_LEVELS = (
        (0, 'Easy'),
        (1, 'Medium'),
        (2, 'Hard'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes_created')
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient')
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    difficulty = models.IntegerField(choices=DIFFICULTY_LEVELS)
    serves = models.PositiveIntegerField()
    image = CloudinaryField('image', default='placeholder')
    status = models.IntegerField(choices=STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """ Meta class for recipe model """
        # pylint: disable=too-few-public-methods
        ordering = ['-created_at']

    def total_time(self):
        """ Calculate total time to cook """
        return self.prep_time + self.cook_time

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    """
    Stores a single ingredient for a particular recipe
    """
    UNIT_CHOICES = (
        # Weight
        ('MG', 'Milligram'),
        ('GRAM', 'Gram'),
        ('KG', 'Kilogram'),
        ('OUNCE', 'Ounce'),
        ('LB', 'Pound'),

        # Volume
        ('ML', 'Milliliter'),
        ('LITRE', 'Litre'),
        ('TSP', 'Teaspoon'),
        ('TBSP', 'Tablespoon'),
        ('CUP', 'Cup'),
        ('PINT', 'Pint'),
        ('QUART', 'Quart'),
        ('GALLON', 'Gallon'),

        # Quantity / Size
        ('SMALL', 'Small'),
        ('MEDIUM', 'Medium'),
        ('LARGE', 'Large'),
        ('PIECE', 'Piece'),
        ('BUNCH', 'Bunch')
    )
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               related_name='ingredients_in_recipe')
    ingredient = models.ForeignKey(Ingredient,
                                   on_delete=models.CASCADE,
                                   related_name='used_in_recipes')
    quantity = models.PositiveIntegerField(default=0)
    unit = models.CharField(max_length=200, choices=UNIT_CHOICES)

    def __str__(self):
        return f"""{self.quantity} {self.get_unit_display()} of
        {self.ingredient.name} in {self.recipe.title}"""


class MealPlan(models.Model):
    """
    Stores a single recipe for a particular meal plan (a collection of recipes)
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meal_plans')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    recipes = models.ManyToManyField(Recipe)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def meal_plan_length(self):
        """ Calculate length of meal plan in days """
        if self.end_date and self.start_date:
            return (self.end_date - self.start_date).days
        return 0

    def __str__(self):
        return f'{self.title} - ({self.start_date} - {self.end_date})'

    def clean(self):
        """ Overwrite base cleaning for model """
        if self.end_date and self.start_date > self.end_date:
            raise ValueError('End date cannot be before start date.')


class Comment(models.Model):
    """
    Stores a single comment for a particular recipe
    """
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments_on_recipe')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments_by_user')
    body = models.TextField()
    approved = models.BooleanField(default=False)
    approver_note = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """ Meta class for comment model """
        # pylint: disable=too-few-public-methods
        ordering = ['-approved', '-created_at']

    def __str__(self):
        return f'Comment by {self.user} on {self.recipe}'

recipe/views.py
""" Module for all django views """
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST
from django.forms import formset_factory
from django.http import JsonResponse
from django.contrib import messages
from django.db import transaction
from django.views import generic
from .forms import RecipeForm, RecipeIngredientForm, MealPlanForm, CommentForm
from .models import Recipe, Ingredient, RecipeIngredient, MealPlan, Comment
from .utils import get_nutrition_info


def home_view(request):
    """ Return the home page view """
    return render(request, 'recipe/index.html')


class RecipeList(generic.ListView):
    """ Return the browse recipe view"""
    model = Recipe
    queryset = Recipe.objects.filter(status=1)
    template_name = "recipe/browse_recipes.html"
    paginate_by = 6


def get_recipe_nutrition_info(recipe):
    """
    Uncomment the above and comment the below when you want to get actual data
    This is done to avoid monthly API limits
    """
    # recipe_ingredients = [
    #     f'{recipe_ing.quantity}{recipe_ing.unit} {recipe_ing.ingredient.name}'
    #     for recipe_ing in recipe.ingredients_in_recipe.all()]
    # total_nutrition = get_nutrition_info(recipe.title, recipe_ingredients)
    total_nutrition = {
        'calories': 500.56462465465464,
        'protein': 150,
        'fat': 14,
        'carbs': 18,
        'fiber': 7.9
    }
    return total_nutrition


@require_POST
def post_recipe_comment(request, recipe_instance):
    """ Send a post request for a new comment """
    comment_form = CommentForm(data=request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.recipe = recipe_instance
        comment.save()
        messages.add_message(
            request, messages.SUCCESS,
            'Comment submitted and awaiting approval'
        )
    else:
        messages.add_message(
            request, messages.ERROR,
            'There was an error submitting your comment. Please try again.'
        )
    return redirect('get_recipe_detail', recipe_pk=recipe_instance.pk)


def handle_recipe_comment_context(recipe_instance):
    """
    Handle comment context for recipe instances
    """
    comments = recipe_instance.comments_on_recipe.all().order_by('-created_at')
    comment_count = comments.filter(approved=True).count()
    comment_form = CommentForm()
    comment_context = {
        'comments': comments,
        'comment_count': comment_count,
        'comment_form': comment_form
    }
    return comment_context


def get_recipe_detail(request, recipe_pk):
    """
    Display details of a recipe, including comments and
    aggregated nutritional information for the entire recipe
    """
    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    if request.POST:
        return post_recipe_comment(request, recipe)

    if request.user.is_authenticated:
        all_meal_plans = MealPlan.objects.filter(user=request.user)
    else:
        all_meal_plans = []
    total_nutrition = get_recipe_nutrition_info(recipe)
    comment_context = handle_recipe_comment_context(recipe)
    context = {
        'recipe': recipe,
        'all_meal_plans': all_meal_plans,
        **total_nutrition,
        **comment_context
    }
    return render(request, 'recipe/recipe_detail.html', context)


@require_POST
def add_recipe_to_meal_plan(request):
    """ Add a recipe to a meal plan """
    data = json.loads(request.body)
    meal_plan_id = data['meal_plan_id']
    recipe_id = data['recipe_id']

    meal_plan = get_object_or_404(MealPlan, pk=meal_plan_id)
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if recipe in meal_plan.recipes.all():
        return JsonResponse({'success': False,
                             'message': 'Recipe already in meal plan.'
                             })

    meal_plan.recipes.add(recipe)
    return JsonResponse({'success': True,
                         'message': 'Recipe added to meal plan successfully!'
                         })


@login_required
def create_or_update_recipe(request, recipe_pk=None):
    """
    Take the user inputted recipe and save it to the database
    """
    recipe_ingredient_form_set = formset_factory(RecipeIngredientForm, extra=3)

    # If there is a recipe_pk then update or else create a new recipe
    if recipe_pk:
        recipe = get_object_or_404(Recipe, pk=recipe_pk)
        is_update = True
    else:
        recipe = None
        is_update = False

    if request.method == 'POST':
        recipe_form = RecipeForm(request.POST, request.FILES, instance=recipe)
        recipe_ing_form_set = recipe_ingredient_form_set(request.POST)

        if recipe_form.is_valid() and recipe_ing_form_set.is_valid():
            with transaction.atomic():
                recipe = recipe_form.save(commit=False)
                recipe.author = request.user
                recipe.save()

                if is_update:
                    recipe.ingredients.clear()

                for recipe_ing_form in recipe_ing_form_set:
                    ingredient = recipe_ing_form.cleaned_data.get('ingredient')
                    RecipeIngredient.objects.create(
                        recipe=recipe,
                        ingredient=ingredient,
                        quantity=recipe_ing_form.cleaned_data.get('quantity'),
                        unit=recipe_ing_form.cleaned_data.get('unit')
                    )

                messages.add_message(
                    request, messages.SUCCESS,
                    'Your recipe has been saved!'
                )
                return redirect('get_recipe_detail', recipe_pk=recipe.pk)
        else:
            if not recipe_form.is_valid():
                form_error = str(recipe_form.errors)
            else:
                form_error = str(recipe_ing_form_set.errors)
            messages.add_message(
                request, messages.ERROR,
                f'Your recipe is not saved! - {form_error}'
            )

    recipe_form = RecipeForm(instance=recipe)
    if is_update:
        initial_ingredients = [
            {'ingredient': recipe.ingredient,
             'quantity': recipe.quantity,
             'unit': recipe.unit}
            for recipe in recipe.ingredients_in_recipe.all()
        ]
        recipe_ing_form_set = recipe_ingredient_form_set(initial=initial_ingredients)
    else:
        recipe_ing_form_set = recipe_ingredient_form_set()
    ingredients = Ingredient.objects.all()
    context = {
        'recipe_form': recipe_form,
        'recipe_ingredient_formset': recipe_ing_form_set,
        'all_ingredients': ingredients,
        'recipe': recipe,
        'is_update': is_update
    }
    return render(request, 'recipe/add_recipe.html', context)


def delete_recipe(request, recipe_pk):
    """
    Delete a recipe
    """
    recipe = get_object_or_404(Recipe, pk=recipe_pk)

    if recipe.author == request.user:
        recipe.delete()
        messages.add_message(
            request, messages.SUCCESS,
            'Recipe deleted!')
    else:
        messages.add_message(
            request, messages.ERROR,
            'You can only delete your own recipe!')

    return redirect('browse_recipes')


@login_required
def create_meal_plan(request):
    """
    Create a meal plan for a user (a meal plan is a collection of recipes)
    """
    if request.method == 'POST':
        meal_plan_form = MealPlanForm(request.POST)

        if meal_plan_form.is_valid():
            with transaction.atomic():
                meal_plan = meal_plan_form.save(commit=False)
                meal_plan.user = request.user
                meal_plan.save()
                meal_plan_form.save_m2m()

            return redirect('get_meal_plan', meal_plan_pk=meal_plan.pk)

    meal_plan_form = MealPlanForm()
    context = {
        'meal_plan_form': meal_plan_form
    }
    return render(request, 'recipe/create_meal_plan.html', context)


class MealPlanList(LoginRequiredMixin, generic.ListView):
    """
    Return the browse meal plan view
    """
    template_name = "recipe/browse_meal_plan.html"
    paginate_by = 8

    def get_queryset(self):
        return MealPlan.objects.filter(user=self.request.user)


@login_required
def get_meal_plan(request, meal_plan_pk):
    """
    Get the meal plan details for a particular meal plan
    """
    meal_plan = get_object_or_404(MealPlan, pk=meal_plan_pk, user=request.user)

    context = {
        'meal_plan': meal_plan}
    return render(request, 'recipe/meal_plan_detail.html', context)


@login_required
@require_POST
def edit_comment(request, recipe_pk, comment_pk):
    """
    Edit existing comment
    """
    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment_form = CommentForm(data=request.POST, instance=comment)

    if comment_form.is_valid() and comment.user == request.user:
        comment = comment_form.save(commit=False)
        comment.recipe = recipe
        comment.approved = False
        comment.save()
        messages.add_message(
            request, messages.SUCCESS,
            'Comment Updated!')
    else:
        messages.add_message(
            request, messages.ERROR,
            'Error updating comment!')

    return redirect('get_recipe_detail', recipe_pk=recipe_pk)


@login_required
def delete_comment(request, recipe_pk, comment_pk):
    """
    Delete existing comment
    """
    comment = get_object_or_404(Comment, pk=comment_pk)

    if comment.user == request.user:
        comment.delete()
        messages.add_message(
            request, messages.SUCCESS,
            'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR,

recipe/templates/recipe/browse_meal_plan.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-title text-center">Browse Meal Plan</h1>
    <div class="row">
        {% for meal_plan in mealplan_list %}
            <div class="col-md-6 col-lg-4">
                <div class="card meal-plan-card mb-4">
                    <div class="card-header">
                        <h5 class="card-title" style="color: #c69c6d;">{{ meal_plan.title}}</h5>
                    </div>
                    <div>
                        <p class="card-text">
                            <strong>Recipe count:</strong> {{ meal_plan.recipes.count }}<br>
                            <strong>Meal Plan length:</strong> {{ meal_plan.meal_plan_length }} days<br>
                            <strong>Start date:</strong> {{ meal_plan.start_date }}<br>
                            <strong>End date:</strong> {{ meal_plan.end_date }}<br>
                        </p>
                        <a href="{% url 'get_meal_plan' meal_plan.id %}" class="btn btn-secondary">View Meal Plan</a>
                    </div>
                </div>
            </div>        
        {% endfor %}
    </div>

    <!-- Page Counter  Can delete if not wanted...-->
    <div class="pagination mt-4">
        <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
    </div>
        
    <!-- Pagination Links -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}

recipe/templates/recipe/browse_recipes.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <h1 class="page-title text-center">Browse Recipes</h1>
    <div class="row">
        {% for recipe in recipe_list %}
        <div class="col-md-6 col-lg-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="image-container">
                    <!-- Recipe Image -->
                    {% if "placeholder" in recipe.image.url %}
                    <img class="card-img-top" src="{% static 'images/default.png' %}" alt="placeholder image">
                    {% else %}
                    <img class="card-img-top" src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
                    {% endif %}
                    <div class="image-flash">
                        <p class="author">Author: {{ recipe.author.username }}</p>
                    </div>
                </div>
                
                <!-- Recipe detail-->
                <div class="card-body">
                    <h5 class="card-title">{{ recipe.title}}</h5>
                    <p class="card-text">
                        <strong>Cook Time:</strong> {{ recipe.total_time }} minutes<br>
                        <strong>Created Date:</strong> {{ recipe.created_at }}<br>
                    </p>
                </div>

                <!-- Link to recipe details -->
                <div class="card-footer">
                    <a href="{% url 'get_recipe_detail' recipe.id %}" class="btn btn-danger">View Recipe</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Page Counter  Can delete if not wanted...-->
    <div class="pagination mt-4">
        <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
    </div>
        
    <!-- Pagination Links -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}

recipe/templates/recipe/create_meal_plan.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1 class="page-title text-center">Create a Meal Plan</h1>
    <hr class="break">
    <form method="POST" enctype="multipart/form-data" action="{% url 'create_meal_plan' %}">
        {% csrf_token %}
        {{ meal_plan_form|crispy }}
        <button type="submit" class="btn btn-secondary">Create Meal Plan</button>
    </form>

</div>
{% endblock %}

recipe/templates/recipe/recipe_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container pt-5">
    <!-- First Container: Recipe Image and Basic Info -->
    <div class="row">
        <div class="col-md-6 image-container">
            {% if "placeholder" in recipe.image.url %}
                <img class="card-img-top" src="{% static 'images/default.png' %}" style="position: relative; border-radius: 10px;" alt="placeholder image">
            {% else %}
                <img class="card-img-top" src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>{{ recipe.title }}</h2>
            <p><strong>Author:</strong> {{ recipe.author.username }}</p>
            <p><strong>Prep Time:</strong> {{ recipe.prep_time }} minutes</p>
            <p><strong>Cook Time:</strong> {{ recipe.cook_time }} minutes</p>
            <p><strong>Difficulty:</strong> {{ recipe.get_difficulty_display }}</p>
            <p><strong>Serves:</strong> {{ recipe.serves }}</p>
            
            <!-- Button for Add to Meal Plan -->
            {% if user.is_authenticated %}
                <button id="add-recipe-to-meal-plan-btn" class="btn btn-primary me-3" data-toggle="modal"
                        data-target="#mealPlanModal">Add to Meal Plan</button>
            {% endif %}

            {% if user == recipe.author %}
                <a type="button" href="{% url 'edit_recipe' recipe.id %}" class="btn btn-primary">Edit Recipe</a>
                <button type="button" id="delete-recipe-btn" class="btn btn-delete" data-recipe-id="{{ recipe.id }}">Delete Recipe</button>
            {% endif %}

        </div>
    </div>

    <!-- Second Container: Ingredients List -->
    <div class="mt-5">
        <h4>Ingredients</h4>
        <ul class="recipe-detail-list">
            {% for recipe_ingredient in recipe.ingredients_in_recipe.all %}
                <li>{{ recipe_ingredient.ingredient.name }} - {{ recipe_ingredient.quantity }} {{ recipe_ingredient.get_unit_display }}</li>
            {% endfor %}            
        </ul>        
    </div>

    <!-- Third Container: Recipe Instructions -->
    <div class="mt-5">
        <h4>Method</h4>
        <div class="card-body">
            <p class="card-text">{{ recipe.description | safe }}</p>
        </div>        
        
        <div class="mt-5 nutrition-info">
            <h4>Nutrition Information</h4>
            <ul class="recipe-detail-list">
                <li>Calories: {{ calories| floatformat:2 }} kcal</li>
                <li>Protein: {{ protein| floatformat:2 }} g</li>
                <li>Fat: {{ fat| floatformat:2 }} g</li>
                <li>Carbohydrates: {{ carbs| floatformat:2 }} g</li>
                <li>Fiber: {{ fiber| floatformat:2 }} g</li>
            </ul>
            <div id="edamam-badge" data-color="white"></div>
        </div>

    </div>

    <!-- Fourth Container: Comments Section -->
    <!-- Displaying count of comments -->
    <div class="row">
        <div class="col-12">
            <strong class="text-secondary">
                <i class="far fa-comments"></i> {{ comment_count }}
            </strong>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>
    <!-- Displaying Comments -->
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags
                to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="p-2 comments
                    {% if not comment.approved and comment.user == user %}
                    faded{% elif not comment.approved %} d-none{% endif %}">
                    <p class="font-weight-bold">
                        {{ comment.user }}
                        <span class="font-weight-normal">
                            {{ comment.created_at }}
                        </span> wrote:
                    </p>
                    <div id="comment{{ comment.id }}">
                        {{ comment.body | linebreaks }}
                    </div>
                    {% if not comment.approved and comment.user == user %}
                    <p class="approval">
                        This comment is awaiting approval
                    </p>
                    {% endif %}
                    {% if user.is_authenticated and comment.user == user %}
                    <button class="btn btn-delete" data-comment_id="{{ comment.id }}">Delete</button>
                    <button class="btn btn-edit" data-comment_id="{{ comment.id }}">Edit</button>
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <!-- Creating New Comments -->
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form id="commentForm" method="post"
                    style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit_button" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <p>Log in to leave a comment</p>
                {% endif %}
            </div>
        </div>
    </div>    
</div>

<!-- Add recipe to meal plan modal -->
<div class="modal fade" id="mealPlanModal" tabindex="-1" aria-labelledby="mealPlanModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mealPlanModalLabel">Add to Meal Plan</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Let's add this recipe to a Meal Plan. Select one below.
                <div class="form-group col-md-4">
                    <select id="meal_plan_dropdown" class="form-control">
                    {% for meal_plan in all_meal_plans %}
                    <option value="{{ meal_plan.id }}">{{ meal_plan.title }}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="confirm_add_to_meal_plan_btn" href="#" class="btn btn-primary">Add to Meal Plan</a>
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel" style="color: black;">Are you sure?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extras %}
<script> const recipeId = "{{recipe.id}}"; </script>
<script src="{% static 'js/comments.js' %}"></script>
<script src="{% static 'js/recipe.js' %}"></script>
<!-- Attribution for nutrition api-->
<script src="https://developer.edamam.com/attribution/badge.js"></script>
{% endblock %}